### PR TITLE
Support syscalls ftruncate64, stat64, lstat64, fstat64, and fcntl64.

### LINKED ISSUE #49: Support syscalls ftruncate64, stat64, lstat64, fstat64, and fcntl64
These syscalls are needed for musl support because musl defaults to using 64-bit versions of these system calls.

The definition of the stat64 structure is derived from here:
https://git.musl-libc.org/cgit/musl/tree/arch/i386/bits/stat.h

The size of underlying types are determined from here:
https://git.musl-libc.org/cgit/musl/tree/include/alltypes.h.in
https://git.musl-libc.org/cgit/musl/tree/arch/i386/bits/alltypes.h.in

Test programs are attached. The first test program uses ftruncate64 to truncate a file to 100 bytes and then calls the three new stat calls to get the size. The second program calls fcntl64 to set close-on-exec for a file handle, then spawns checkfd to verify that the handle is closed.

This is the expected output:

```
[(root) ~]# tar xf test64.tar.gz
[(root) ~]# ./runtest.sh
1000+0 records in
1000+0 records out
1000 bytes (1.0 kB) copied, 0.003208 s, 312 kB/s
stat64: file size is 100
lstat64: file size is 100
fstat64: file size is 100
-rw-r--r-- 1 root root 100 Nov 28 16:48 testfile.bin
myfile = 3
mydupfd = 4
mycheck result = -1
```
[test64.tar.gz](https://github.com/mikaku/Fiwix/files/13491313/test64.tar.gz)

### PR DESCRIPTION
**Pull request by rick-masters**
Closes #49

### CODE REVIEW

**Comment by mikaku** [comment]
Before checking the code in its own, I've see some issues I'd like to discuss:

1. `(unsigned) long int` must not be used on i386 code since is the same as `(unsigned) int` (4 bytes). We must try to avoid this type of data, otherwise the code could create confusion when adding support for a 64bit architecture.
2. I don't see a correlation between https://git.musl-libc.org/cgit/musl/tree/arch/i386/bits/stat.h and the same file provided in the PR or even with the file in Linux 2.4 kernel (should I look at Linux 2.6?) . For instance, `st_dev` is defined as `unsigned long long` (8 bytes) in your PR but is defined as `dev_t` in musl which I presume is a 32bit field as in Linux 2.4.
3. Why `F_GETLK64`, `F_SETLK64` and `F_SETLKW64` aren't declared as 12, 13 and 14 respectively as in Linux 2.4?

**Comment by rick-masters** [comment]
> Before checking the code in its own, I've seen some issues I'd like to discuss:
> 
> 1. `(unsigned) long int` must not be used on i386 code since is the same as `(unsigned) int` (4 bytes). We must try to avoid this type of data, otherwise the code could create confusion when adding support for a 64bit architecture.

Can you suggest a type to use? Would __s32 be ok? If not, what type?

> 2. I don't see a correlation between https://git.musl-libc.org/cgit/musl/tree/arch/i386/bits/stat.h and the same file provided in the PR or even with the file in Linux 2.4 kernel (should I look at Linux 2.6?) . For instance, `st_dev` is defined as `unsigned long long` (8 bytes) in your PR but is defined as `dev_t` in musl which I presume is a 32bit field as in Linux 2.4.

I believe the struture in the PR is consistent with musl.
dev_t is a 64-bit field in musl. See line 31 here:
https://git.musl-libc.org/cgit/musl/tree/include/alltypes.h.in


> 3. Why `F_GETLK64`, `F_SETLK64` and `F_SETLKW64` aren't declared as 12, 13 and 14 respectively as in Linux 2.4?

I'll fix this, thanks. 
I copied the #define from musl but that doesn't work in Fiwix for confusing reasons. musl always forces the 64-bit syscalls (e.g. fcntl64) so the underlying F_GETLK is also forced to the 64-bit value (12) so the #define works in musl. But that doesn't work in Fiwix because it supports the 32-bit fcntl and so F_GETLK is not 12.

**Comment by mikaku** [comment]
> Can you suggest a type to use? Would __s32 be ok? If not, what type?

For 32bit data types you can use `(unsigned) int`, not `(unsigned) long int`. I mean, we need to avoid using the word `long` when defining 32bit data types. We should rename those `long` by `int` since they are the same on an i386.

Also, data types should have complete names. I mean, not just `unsigned`, but `unsigned int`.

> I believe the struture in the PR is consistent with musl.
dev_t is a 64-bit field in musl. See line 31 here:

Oh, I see, forget it. I was just comparing it with the `statfs64` in https://elixir.bootlin.com/linux/2.4.31/source/include/asm-i386/stat.h. And those extra padding fields confused me.

The structure looks consistent indeed.

**Comment by mikaku** [comment]
Thank you.

**Comment by mikaku** [comment]
> I figured that limitation didn't matter because I thought the Fiwix filesystems were limited to 32-bit sizes anyway.

I've checked limits in Fiwix ext2 filesystems and I think (not fully tested) the file size is limited by `i_size` since Fiwix is not taking advantage of the field `i_dir_acl` as the higher 4 bytes of `i_size` (for files only, of course) as Linux 2.2 does.

So, although an ext2 file system can be as big as 128GiB, the maximum size for files will be 4GiB.

**Pull request merged**
