### PR TITLE
Implement mmap2 system call.

### LINKED ISSUE #47: Support syscall mmap2
Please support syscall mmap2.
mmap2 is similar to mmap except that the offset argument is multiplied by 4096 to compute the effective offset.
This supports very large offsets for very large files.
The mmap2 system call is used by the musl C library to implement mmap, so mmap2 is needed for musl even if large offsets are not needed.

mmap2 takes 6 arguments which requires CONFIG_SYSCALL_6TH_ARG to be set.
For this reason, mmap2 is defined behind CONFIG_MMAP2.

For testing, both CONFIG_SYSCALL_6TH_ARG and CONFIG_MMAP2 should be set.
A custom_config.h can be used for this purpose like so:

```
echo '#define CONFIG_SYSCALL_6TH_ARG' > include/fiwix/custom_config.h
echo '#define CONFIG_MMAP2' >> include/fiwix/custom_config.h
make clean
make CONFFLAGS="-DCUSTOM_CONFIG_H"
```

A test program for mmap2 and a test script to build and run the test program is attached.
The test script produces an input file with random data and the runs the test program.
The test program mmap's the input file and output file with an offset of 4096.
The test program then copies data from the input file to the output file using memory.

The test script then extracts the contents of the input and output file starting with offset 4096 and verifies that they are the same.
[mmap2-test.c.gz](https://github.com/mikaku/Fiwix/files/13281203/mmap2-test.c.gz)
[mmap2.sh.gz](https://github.com/mikaku/Fiwix/files/13281204/mmap2.sh.gz)

### PR DESCRIPTION
**Pull request by rick-masters**
Closes #47

### CODE REVIEW

**Comment by mikaku** [comment]
I'd enclose the file `kernel/syscalls/mmap2` with a `#define CONFIG_SYSCALL_6TH_ARG` starting right before the line 21, basically because it is no so evident that someone will also need that option to make `sys_mmap2()` work.

I mean, the rest of kernel options are (or should be) working without knowing any kind of dependency that is not visible in the same source file.

**Comment by rick-masters** [comment]
> I'd enclose the file `kernel/syscalls/mmap2` with a `#define CONFIG_SYSCALL_6TH_ARG` starting right before the line 21

Do you mean #ifdef CONFIG_SYSCALL_6TH_ARG ?

**Comment by mikaku** [comment]
> Do you mean #ifdef CONFIG_SYSCALL_6TH_ARG ?

Oh yes, sorry.

**Comment by mikaku** [comment]
@rick-masters Let me remind you that I plan to do a code freeze in two days because I need some time to prepare the build of the new FiwixOS 3.3 that will include the Fiwix version 1.5.0.

So if you still have some pending ports, please choose the smaller ones and leave the bigger ones for later.

**Comment by rick-masters** [comment]
> @rick-masters Let me remind you that I plan to do a code freeze in two days because I need some time to prepare the build of the new FiwixOS 3.3 that will include the Fiwix version 1.5.0.
> 
> So if you still have some pending ports, please choose the smaller ones and leave the bigger ones for later.

OK I can hold off changes until after the release.

**Comment by mikaku** [comment]
> OK I can hold off changes until after the release.

That's perfect. The release should publicly available on 15 November.

Thank you.

**Pull request merged**
